### ISSUE TITLE
Preconditioning issue.

### ISSUE THREAD

**Issue by bluntiless** [WonkiDonk/homebridge-jlr-incontrol#5]
Hello @WonkiDonk I have just installed your plugin. Great work and thanks! I have locking and unlocking working appropriately, but unfortunately preconditioning does not. It says there is no response. I am using it with the E-Pace. Terminal in DEBUG outputs this:
[2019-4-8 10:46:30] [E-PACE] Set heating cooling state to 1
[2019-4-8 10:46:30] [E-PACE] Getting active session
[2019-4-8 10:46:30] [E-PACE] Getting command token ECC
[2019-4-8 10:46:30] [E-PACE] Sending preconditioning command [ { key: 'PRECONDITIONING', value: 'START' },
  { key: 'TARGET_TEMPERATURE_CELSIUS', value: 285 } ]
[2019-4-8 10:46:30] [E-PACE] Set heating cooling state to 0
[2019-4-8 10:46:30] [E-PACE] Getting active session
[2019-4-8 10:46:30] [E-PACE] Getting command token ECC
[2019-4-8 10:46:31] [E-PACE] Sending preconditioning command [ { key: 'PRECONDITIONING', value: 'STOP' } ]

It seems it is telling it to start and then stop. Any advice would be appreciated.

**Comment by WonkiDonk** [comment]
I'll take a look. Do you have it set to 28.5 degrees? How're you turning on the preconditioning? Setting it to "Heat", "Cool" or "Auto"?

**Comment by bluntiless** [comment]
Thanks for replying @WonkiDonk. I have tried heat, cool and Auto. On the above Terminal output, I think if I remember correctly, it was set to Heat. Oh and yes, it was set to 28.5 degrees. I did try a number of different temperatures.

**Comment by WonkiDonk** [comment]
OK. I wasn't able to reproduce on my local version, however, I was a little ahead and had definitely changed this code. I've released v0.3. Could you upgrade and try again.

Also you may have noticed an issue where tokens weren't properly expiring so you might have had a "No response" in the Apple Home app. That's now been resolved, too! :-)

Let me know if you can still reproduce.

**Comment by bluntiless** [comment]
Hi again. So I have updated to your latest version and unfortunately it is still the same. Do you think it might be the deviceId, as I just made this up. Where are you supposed to get this from?

**Comment by WonkiDonk** [comment]
It _shouldn't_ be the `deviceId`. This is just a unique value that identifies your device. I just use a random `Guid` for mine.

From your logs, it looks like it's activating then immediately deactivating the climate control. It looks like the request to deactivate is coming directly from iOS rather than the plug-in itself...

What version of iOS are you using?

**Comment by bluntiless** [comment]
Hi again, my phone is on iOS 12.2 beta.

**Comment by dopefish3d** [comment]
hey there, just learned about HomeBridge last week and saw this jlr plugin today.  I seem to be having a similar problem to bluntiless.  I can get lock/unlock to work (although it doesn't seem terribly reliable), but when attempting to precondition the car (i have a '19 LR Velar) it appears to just turn itself back off a few seconds later (in the Home app, the physical car never appears to do anything at all).    Also is there a way to suppress the "Charger" switch? As my car is a gasoline car.

**Comment by woots82** [comment]
Hey just wondering if this is compatible with a 2014 Evoque?

**Comment by WonkiDonk** [comment]
Fixed. Not sure if it is compatible with Evoque, give it a try!

**Comment by WonkiDonk** [comment]
> hey there, just learned about HomeBridge last week and saw this jlr plugin today. I seem to be having a similar problem to bluntiless. I can get lock/unlock to work (although it doesn't seem terribly reliable), but when attempting to precondition the car (i have a '19 LR Velar) it appears to just turn itself back off a few seconds later (in the Home app, the physical car never appears to do anything at all). Also is there a way to suppress the "Charger" switch? As my car is a gasoline car.

Raise a separate ticket, I'll make a switch

**Comment by WonkiDonk** [comment]
> hey there, just learned about HomeBridge last week and saw this jlr plugin today. I seem to be having a similar problem to bluntiless. I can get lock/unlock to work (although it doesn't seem terribly reliable), but when attempting to precondition the car (i have a '19 LR Velar) it appears to just turn itself back off a few seconds later (in the Home app, the physical car never appears to do anything at all). Also is there a way to suppress the "Charger" switch? As my car is a gasoline car.

Update to v0.7 and add the following config:
```json
{
  ...
  "disableEV": true
}
```
